Interpret square root op.
openxla/stablehlo pull request #1068
Opened 2023-02-06 14:04 UTC by subhankarshah

2023-02-06 19:00 UTC, ghpvnist requested changes
I encourage you to refer to our [reference_checklist](https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md) to ensure there's no missing files.

2023-02-06 19:00 UTC, ghpvnist commented on stablehlo/tests/interpret_square_root.mlir
> +func.func @square_root_op_test_c64() -> tensor<2xcomplex<f32>> {
According to the [testing_guidelines](https://github.com/openxla/stablehlo/blob/main/docs/reference.md#testing-guidelines), we should be testing with the maximum bit-width for each type:
```
func.func @square_root_op_test_c128() -> tensor<2xcomplex<f64>> {
```

2023-02-06 19:24 UTC, ghpvnist requested changes
I made similar comment to #1008. PTAL

2023-02-07 00:38 UTC, ghpvnist approved these changes

2023-02-08 03:22 UTC, sdasgup3 approved these changes
For completeness add the testing strategy (https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md). In this case, we will end up with no up if we follow  https://github.com/openxla/stablehlo/pull/996#issue-1558631158

2023-02-09 19:05 UTC, ghpvnist commented
Linking issue: [Make sure that examples in the spec/ODS conform to spec_checklist.md](#454)

2023-02-10 21:19 UTC, sdasgup3 commented on stablehlo/dialect/StablehloOps.td
> +  let summary = "Sqrt operation";
Add input constraints as per  the checklist.

2023-02-14 03:54 UTC, burmako requested changes

2023-02-14 03:54 UTC, burmako commented on docs/spec.md
>  // %operand: [[0.0, 1.0], [4.0, 9.0]]
Please update the PR description to follow the testing guidelines, e.g. similarly to #1080.

2023-02-16 20:27 UTC, burmako approved these changes

2023-02-16 20:39 UTC, sdasgup3 approved these changes

2023-02-21 11:38 UTC, merged