Add interpreter for RsqrtOp.
openxla/stablehlo pull request #1085
Opened 2023-02-08 01:57 UTC by subhankarshah

closes #986

2023-02-09 01:45 UTC, ghpvnist requested changes
Can you also update the PR description about the constraint as mentioned in the [reference_checklist](https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md):

> Provide an explicitly written down testing strategy (in a PR description) similar to https://github.com/openxla/stablehlo/pull/996#issue-1558631158 to use it as a reference while reviewing the verification and type inference methods, and the corresponding tests. The reviewer will double check that the description is comprehensive.

2023-02-09 01:45 UTC, ghpvnist commented on stablehlo/reference/Element.cpp
> +      el, [](double e) { return static_cast<double>(1) / std::sqrt(e); },
`1.0 / std::sqrt(e)`?

2023-02-10 21:19 UTC, sdasgup3 commented on stablehlo/dialect/StablehloOps.td
> +  let summary = "Rsqrt operation";
Add input constraints as per  the checklist.

2023-02-13 23:10 UTC, ghpvnist commented
Please rebase this change on top of main. You'll also have to modify `Ops.pp` to include changes from `Interpreter.cpp` which is now merged into `Ops.cpp`.

2023-02-13 23:12 UTC, ghpvnist requested changes
Can you also update the PR description to include with consideration of constraints reviewed?

2023-02-13 23:12 UTC, ghpvnist commented on stablehlo/reference/Ops.cpp
> +  for (auto it = result.index_begin(); it != result.index_end(); ++it)
`it` -> `resultIt`

2023-02-16 20:42 UTC, sdasgup3 approved these changes

2023-02-16 20:42 UTC, sdasgup3 commented on stablehlo/reference/Element.h
> +/// Returns floor of Element object.
Good catch!

2023-02-22 02:37 UTC, burmako approved these changes

2023-02-22 21:01 UTC, merged