Don't load Tensor dialect in StableHLO dialect constructor
openxla/stablehlo pull request #1088
Opened 2023-02-08 20:57 UTC by burmako

I recently noticed this code when reviewing #849, and I'm not sure why we need it there.

This seems like a pretty strong statement about a fundamental role of the Tensor dialect in the workings of the StableHLO dialect, and I don't think we have established that yet.

It would seem that we've inherited this from MHLO when bootstrapping StableHLO (#1), but I don't think I understand the reasoning on the MHLO side either. This change was introduced as part of an LLVM integrate (https://github.com/tensorflow/mlir-hlo/commit/ba0346b071f4212008943c50f47766e677992b56), and the commit description doesn't go into detail about motivation.

Given that, I propose to revert this in the StableHLO dialect and see what happens. All tests in this repository are passing, but maybe we'll learn more after downstream integrations.

2023-02-08 21:30 UTC, GleasonK requested changes
LGTM

Thoughts on removing TensorDialect from `registerAllDialects` as well? Seems we have an equal reliance (maybe even less of a reliance) on TensorDialect as we do quant and sparse, and we removed those from `registerAllDialects`.

2023-02-08 21:31 UTC, GleasonK commented
Edit, I misspoke, its `registry.insert<mlir::sparse_tensor::SparseTensorDialect>();` in register all. Any idea if that should be there?

2023-02-08 21:32 UTC, GleasonK approved these changes

2023-02-08 22:23 UTC, burmako commented
That's a good question! Opened #1089 to follow up on that.

2023-02-08 22:24 UTC, merged

2023-02-09 20:55 UTC, GleasonK commented
This change caused failures in the following testpoint in TF: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tests/xla_call_module_test.py#L211

We likely need to load this dialect _somewhere_ in the xla pipeline.

2023-02-09 21:57 UTC, burmako commented
Oof I think this shows that removing the Tensor dialect from the StableHLO dialect constructor was the right thing to do. Looks like this test started depending on this unintended behavior, instead of explicitly declaring the dependency on the Tensor dialect in its context initialization.