Migrate VHLO to use properties
openxla/stablehlo pull request #1827
Opened 2023-11-07 22:15 UTC by GleasonK

[MLIR Properties](https://mlir.llvm.org/OpenMeetings/2023-02-09-Properties.pdf) are the new standard for non-discardable attributes. In the near future, all dialects must migrate to use properties by default. This PR migrates VHLO first, which is an important step since we need to ensure:
1. Backward compatibility: VHLO with properties can read older portable artifacts
2. Forward compatibility: VHLO with properties can generate portable artifacts that is readable in previous versions

(1) Had no issues, after migrating VHLO to properties, only the FileCheck lines needed to be updated, note no changes to `stablehlo_legalize_to_vhlo.0_9_0.mlir.bc` for example, meaning we can still read old bytecode files and it deserializes into properties successfully.

(2) Worked fine for all versions of StableHLO **except for 0.14.0**. Note again that there were no changes to `stablehlo_legalize_to_vhlo.0_9_0.mlir.bc`, which means that bytecode files generated at HEAD with properties and targeting 0.9.0 generated _identical_ bytecode files. However, [MLIR Bytecode format v5+](https://github.com/llvm/llvm-project/blob/2e6f722b88e42bba72af5bafd8cc1e37e460d978/mlir/include/mlir/Bytecode/Encoding.h#L48) generates different bytecode for dialects that use properties, and property definitions must be present for deserialization of these. This means back-deployment from `HEAD->0.14.0` breaks, since 0.14.X (pre-properties) doesn't have the property struct definitions needed for deserialization.

Given that backward compatibility is fully supported, (2) is resolved by changing 0.14.0 to target bytecode v4, which serializes attr-dict (can be deserialized by pre/post-property VHLO), and in addition bumping the StableHLO version to 0.15.0 which uses the latest bytecode format version v6. This leads to full forward/backward compatibility with no temporary breakages.

2023-11-07 22:25 UTC, burmako requested changes

2023-11-07 22:25 UTC, burmako commented on stablehlo/dialect/Version.cpp
> +  if (*this < Version(0, 15, 0)) return 4;
I think this needs a comment that explains that this used to be a 5, with an explanation why this change was made.

2023-11-07 22:25 UTC, burmako commented on stablehlo/dialect/VhloDialect.td
>        0.14.0: MLIR bytecode version 3 => 5.
This needs to be updated as well?

2023-11-07 23:58 UTC, ghpvnist approved these changes
LGTM with one question. Should we tag this version separately from the integrates?

2023-11-08 00:08 UTC, GleasonK commented
> LGTM with one question. Should we tag this version separately from the integrates?


We can, wouldn't call it a requirement since the next regular integrate will:
1. Import these changes to openxla/xla
2. Tag StableHLO 0.15.0 
3. Bump revision to 0.15.1

2023-11-08 15:54 UTC, merged