Rename function to closely match spec
openxla/stablehlo pull request #1987
Opened 2024-02-05 18:28 UTC by ghpvnist

As an example, looking at the spec of `collective_broadcast`, we come across the statement:

`broadcast_in_dim(constant(0, element_type(result)), [], type(result))` otherwise.

This PR renames `makeScalar()` to `constant()` with arguments matching the spec above for parity.

2024-02-05 18:35 UTC, GleasonK approved these changes

2024-02-05 18:36 UTC, GleasonK requested changes
Bazel CI failing, unclear why, looks like some change is needed?

2024-02-06 15:34 UTC, mlevesquedion approved these changes
Nice!

2024-02-06 20:32 UTC, GleasonK approved these changes

2024-02-07 01:03 UTC, merged