[RFC] Standardize CustomCallOp to extend backend_config to take a DictionaryAttr
openxla/stablehlo pull request #2097
Opened 2024-03-15 16:11 UTC by abhigunj

This RFC proposes standardizing CustomCallOp to extend backend_config to take a DictionaryAttr for HLO-StableHLO parity.

2024-03-18 20:38 UTC, mlevesquedion approved these changes

2024-03-21 19:05 UTC, ghpvnist approved these changes
LGTM with minor comments

2024-03-21 19:05 UTC, ghpvnist commented on rfcs/20240312-standardize-customcallop.md
> +Jax uses [unregistered attributes](https://github.com/google/jax/blob/1ed27ecebb92e916b45601e3a107971170a4592b/jaxlib/hlo_helpers.py#L191)
Nit: JAX

2024-03-21 20:16 UTC, mlevesquedion commented on docs/spec.md
> +  backend_config = {bar = 42 : i32},
I'm pretty sure this is correct? MLIR doesn't insert spaces between the brackets and the content:

```
$ stablehlo-opt <<<"func.func @foo() {
  stablehlo.composite \"foo.op\" {
    composite_attributes = { bar = 42 : i32 },
    decomposition = @foo
  } : () -> ()
  func.return
}"""
module {
  func.func @foo() {
    stablehlo.composite "foo.op"  {composite_attributes = {bar = 42 : i32}, decomposition = @foo} : () -> ()
    return
  }
}
```
(this uses composite but the idea is the same)

2024-03-21 20:43 UTC, ghpvnist commented on docs/spec.md
> +  backend_config = {bar = 42 : i32},
Hm you're right, looks like our spec needs some updates. I'll create a separate PR to fix them, you can ignore this comment!

2024-03-26 19:30 UTC, sdasgup3 approved these changes

2024-03-26 20:19 UTC, GleasonK requested changes
Adding comment to block until we have community alignment / a chance to socialize this further internally+externally

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +StableHLO `custom_call` op does not support this feature. There are several
nit: "The current" StableHLO `custom_call`

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +to pass around for StableHLO `custom_call` op.
nit: "the" StableHLO

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +We propose standardizing StableHLO `custom_call` op to extend `backend_config`
nit: "the" StableHLO `custom_call` op

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +to take a `DictionaryAttr`.  So they can be used safely by the community without
nit: to take a `DictionaryAttr` so they can be used ...

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +workarounds. It will help to unify metadata under single `DictionaryAttr` which
nit: It -> This

2024-05-16 16:47 UTC, cantonios commented on rfcs/20240312-standardize-customcallop.md
> +workarounds. It will help to unify metadata under single `DictionaryAttr` which
nit: under "a" single `DictionaryAttr`

2024-06-25 17:51 UTC, GleasonK approved these changes

2024-06-25 17:53 UTC, merged