Enforce compatible indices and shape while indexing into Tensor
openxla/stablehlo pull request #215
Opened 2022-09-29 02:01 UTC by sdasgup3

Ideally, we are supposed to use valid indices from the index space of a Tensor to access individual elements. An invalid index might lead of OOB access. While testing the interpreter we found that the eval function of cosine op is still using the linearized index to access the tensor elements. 

```
Tensor eval(CosineOp op, const Tensor &operand) {
  Tensor result(op.getType());
  for (auto i = 0; i < operand.getNumElements(); ++i) {
    result.set(i, cosine(operand.get(i)));
  }
  return result;
}
``` 

While calling the `Tensor::get(rrayRef<int64_t>)`  API, these linear indices are implicitly converted to an `ArrayRef<int64_t>` of size 1. For a tensor with >= 1 rank, these are illegal indices and might cause OOB based on the shape and choice of index. 
We realized that it is  left over  from https://github.com/openxla/stablehlo/pull/167 which we fix here (to use multi-dimensional index instead).

Next the PR add checks, in `flatenIndex` and `IndexSpaceIterator::IndexSpaceIterator`, to ensure that index is compatible with the shape of the tensor.

2022-09-29 04:05 UTC, burmako requested changes

2022-09-29 04:05 UTC, burmako commented on stablehlo/reference/Tensor.cpp
> +  }
Let's deduplicate by adding a `LogicalResult verifyIndex(ArrayRef<int64_t> shape, ArrayRef<int64_t> index)` function in Index.h.

2022-09-29 04:05 UTC, burmako commented on stablehlo/reference/Tensor.cpp
> +      })) {
There's quite a bit of noise here with the tuple type and std::get, if we compare this with an equivalent for loop:

```
for (auto [shapeDim, indexDim] : llvm::zip(shape, index)) {
  if (indexDim < 0 || indexDim >= shapeDim) 
    llvm::report_fatal_error(...)
}
```

2022-09-29 19:40 UTC, sdasgup3 commented
Added some comments to verifyIndex.
Removed the check  `dimension-size < 0` as that can be inferred from the index check.

2022-09-29 19:59 UTC, burmako requested changes

2022-09-29 19:59 UTC, burmako commented on stablehlo/reference/Ops.cpp
>    }
Let's also change `tanh` which also uses the old style of writing eval functions?

2022-09-29 19:59 UTC, burmako commented on stablehlo/reference/Index.h
> +/// {0, 1, ..., R-1}. Note that the check also implies that 'd[k]' >= 1.
That's a good point! Sounds like `index_begin` will now start crashing for tensors with dimensions equal to zero? Let's update `index_begin` to return `{}` in that case and update tests accordingly?

2022-09-30 01:01 UTC, burmako approved these changes

2022-09-30 01:44 UTC, merged