Add TanOp to StableHLO Opset
openxla/stablehlo pull request #2177
Opened 2024-04-08 19:19 UTC by abhigunj

RFC: https://github.com/openxla/stablehlo/pull/2101

This PR include
* OP def 
* reference implementation, test cases
* VHLO change and test cases

2024-07-15 17:41 UTC, ghpvnist commented on docs/spec.md
> +Performs element-wise tangent operation on the `operand` tensor and
Adhering to 80-char line:
```
Performs element-wise tangent operation on the `operand` tensor and produces a
`result` tensor. Depending on the element type, does the following:
```

2024-07-15 21:58 UTC, GleasonK requested changes
Requires version bump to v4, please refer to vhlo_checklist for required changes (VhloDialect.td comment / testing / etc.)

2024-07-15 23:22 UTC, abhigunj commented
> Requires version bump to v4, please refer to vhlo_checklist for required changes (VhloDialect.td comment / testing / etc.)

Thank you. updated PR with version bump and required changes. PTAL.

2024-07-16 15:41 UTC, GleasonK approved these changes

2024-07-16 15:41 UTC, merged