Integrate LLVM at llvm/llvm-project@3a8316216807
openxla/stablehlo pull request #2318
Opened 2024-05-10 01:17 UTC by abhigunj

2024-05-10 01:18 UTC, GleasonK approved these changes

2024-05-10 01:19 UTC, mlevesquedion requested changes
I think the `a.sh` script shouldn't be here?

2024-05-10 01:19 UTC, ghpvnist approved these changes

2024-05-10 01:19 UTC, ghpvnist commented on a.sh
Remove?

2024-05-10 01:19 UTC, abhigunj commented
There are few expected test failures with the latest commit,  updating PR...

2024-05-11 01:59 UTC, abhigunj commented on .github/workflows/buildAndTestCMake.yml
> +          ASAN_OPTIONS: allow_user_poisoning=false
removal tracker https://github.com/openxla/stablehlo/issues/2326

2024-05-13 16:44 UTC, GleasonK approved these changes

2024-05-13 17:05 UTC, merged