Refactor error handling code
openxla/stablehlo pull request #232
Opened 2022-09-30 23:36 UTC by ghpvnist

2022-10-01 01:10 UTC, sdasgup3 commented
It is better to update the PR description with the need of this change. Maybe like "Error handling is need in almost all the files and currently we are not reusing the error handling code"

2022-10-03 21:30 UTC, burmako requested changes
It's a great idea to deduplicate error handling! I've left a few requested changes.

2022-10-03 21:53 UTC, sdasgup3 commented
@burmako @ghpvnist 

At this point we are using a mix of the following variants of `report_fatal_error`
(1) https://github.com/llvm/llvm-project/blob/fdadb5c146960c526f247c829a360f3dae825d8a/llvm/include/llvm/Support/Error.h#L730
(2) https://github.com/llvm/llvm-project/blob/fdadb5c146960c526f247c829a360f3dae825d8a/llvm/include/llvm/Support/ErrorHandling.h#L71

I do not think the interpreter is handling the errors any differently in these two cases. We just report and abort. 
Why not to use (2) consistently, then we may not need any of the above boilerplate.

What do guys think?

2022-10-07 18:49 UTC, ghpvnist commented
> @burmako @ghpvnist
> 
> At this point we are using a mix of the following variants of `report_fatal_error` (1) https://github.com/llvm/llvm-project/blob/fdadb5c146960c526f247c829a360f3dae825d8a/llvm/include/llvm/Support/Error.h#L730 (2) https://github.com/llvm/llvm-project/blob/fdadb5c146960c526f247c829a360f3dae825d8a/llvm/include/llvm/Support/ErrorHandling.h#L71
> 
> I do not think the interpreter is handling the errors any differently in these two cases. We just report and abort. Why not to use (2) consistently, then we may not need any of the above boilerplate.
> 
> What do guys think?

I agree that we should also unify the use of error handling as well. Do you have preference over (2)? @burmako

2022-10-07 19:35 UTC, burmako commented
How would (2) look like exactly? What I like about (1) is that it hides some of the details of string formatting, e.g. I like being able to say `("Expected one region in func %s", func.getName().str().c_str())` instead of stuff like `StringRef("Unsupported type: ") + debugString(type)`.

By the way, it would be even better if we could say `("Expected one region in func %s", func.getName())`, but that's probably a different story.

2022-10-14 00:40 UTC, sdasgup3 commented
>> How would (2) look like exactly? What I like about (1) is that it hides some of the details of string formatting, e.g. I like being able to say ("Expected one region in func %s", func.getName().str().c_str()) instead of stuff like StringRef("Unsupported type: ") + debugString(type).

Yes I was suggesting the concatenating StringRefs using + operators using (2). 

makes sense with your point.

2022-10-14 03:05 UTC, burmako approved these changes

2022-10-14 03:05 UTC, burmako commented on stablehlo/reference/Errors.h
> +#define STABLHLO_REFERENCE_ERRORS_H
Typo: "STABLEHLO".

2022-10-14 17:34 UTC, ghpvnist commented on stablehlo/reference/Errors.h
> +#define STABLHLO_REFERENCE_ERRORS_H
Thanks for the catch!

2022-10-14 17:34 UTC, merged