Testdata files for quantized  programs : GatherOP
openxla/stablehlo pull request #2502
Opened 2024-08-20 01:17 UTC by abhigunj

2024-08-21 03:27 UTC, sdasgup3 approved these changes

2024-08-21 03:27 UTC, sdasgup3 commented on gather_from_slicing_name___0_1___enable_xla_True_qi8.mlir
> +// RUN: stablehlo-translate --interpret -split-input-file %s
Why are these tests not part of testdata/quantized folder?

2024-08-21 03:30 UTC, sdasgup3 requested changes
Please make sure that the golden results are validated against the HLO interpreter `run_hlo_module`

2024-08-23 16:47 UTC, abhigunj commented
> Please make sure that the golden results are validated against the HLO interpreter `run_hlo_module`

Validated, thanks for the review.

2024-08-23 16:53 UTC, sdasgup3 approved these changes

2024-08-23 16:58 UTC, merged