Add spec for ComplexOp
openxla/stablehlo pull request #493
Opened 2022-11-09 20:11 UTC by ghpvnist

closes #468

2022-11-09 20:12 UTC, ghpvnist commented
Verification is `revisit` since the verifier currently allows `lhs` and `rhs` to have different floating-point element type. Issue raised in #492

2022-11-10 16:48 UTC, sdasgup3 approved these changes

2022-11-10 16:48 UTC, sdasgup3 commented on docs/spec_draft.md
> +  * (C1) `lhs` and `rhs` have the same floating-point element type.
How about element_type(`lhs`) $=$ element_type(`rhs`). As we already mentioned that the element type is floating point in the table.

2022-11-10 18:26 UTC, burmako requested changes

2022-11-10 18:26 UTC, burmako commented on docs/status.md
> +| complex                  | yes           | revisit      | yes            | yes             | no          |
Given the discussion in #492, I think that Verification should be "yes".

2022-11-10 18:54 UTC, burmako requested changes

2022-11-10 18:54 UTC, burmako commented on docs/spec_draft.md
> +    element_type(`result`).
Also, not sure if it's just me, but it feels more natural to express C2 and C3 `with element_type(result)` on the left-hand side of the equation, i.e.:

```
  * (C2) `shape(result) = shape(lhs)`.
  * (C3) `element_type(result) = complex_type(element_type(lhs))`.
```

This way, it's also easier to implement type inference for this op based on the Constraints section. It's not hard to invert `element_type(lhs) = real_type(element_type(result))` - but it feels awkward. Given how many times I wrote "feels", this is not a blocking comment, and we can leave figuring this out to #289.

2022-11-11 02:04 UTC, burmako approved these changes

2022-11-11 02:05 UTC, merged