spec-draft: floor/ceil
openxla/stablehlo pull request #72
Opened 2022-09-02 07:26 UTC by sdasgup3

closes https://github.com/openxla/stablehlo/issues/71

Also, fixes some typos in he specification docs.

2022-09-05 22:01 UTC, burmako requested changes

2022-09-06 03:25 UTC, burmako commented on docs/spec_draft.md
> +| `operand` | tensor of floating-point element types |
Nevermind: I see that both HLO and MHLO rejects float/ceil for complex types, which I think is good enough signal for the draft version of the spec that we should reject them too: https://github.com/tensorflow/tensorflow/blob/05216942e9d44901b2831f332624794b40e630ca/tensorflow/compiler/xla/service/shape_inference.cc#L246-L256.

2022-09-06 23:09 UTC, sdasgup3 commented on docs/spec_draft.md
> +         less than or equal to the value.
Added the clarification along with the ops itself.

2022-09-07 00:24 UTC, burmako requested changes

2022-09-07 00:24 UTC, burmako commented on docs/spec_draft.md
> +         towards positive infinity operation from the IEEE-754 specification.
"where ceil of a floating-point value is defined as the smallest integer greater than or equal to the value". Let's drop this, now that we have a reference to IEEE-754.

2022-09-07 00:24 UTC, burmako commented on docs/spec_draft.md
> +         less than or equal to the value. Implements the rounding to integral
This as well.

2022-09-07 00:31 UTC, burmako approved these changes

2022-09-07 01:21 UTC, merged