Fix examples to include operand and result names
openxla/stablehlo pull request #84
Opened 2022-09-03 00:46 UTC by ghpvnist

fixes #80 and minor typos

2022-09-03 00:54 UTC, sdasgup3 requested changes

2022-09-03 00:54 UTC, sdasgup3 commented on docs/spec_draft.md
> +| `value` | `tensor` of any supported type |
types?
here and below

2022-09-06 17:52 UTC, ghpvnist commented on docs/spec_draft.md
> +| `value` | `tensor` of any supported type |
Done

2022-09-06 19:03 UTC, sdasgup3 approved these changes

2022-09-06 19:08 UTC, merged