Handle bounds in the ReduceWindowOp shape function
openxla/stablehlo pull request #916
Opened 2023-01-11 22:12 UTC by ghpvnist

closes #753

2023-01-14 00:30 UTC, smit-hinsu commented on stablehlo/dialect/TypeInference.cpp
> +      auto inputRankedType = inputs[i].getType().cast<RankedTensorType>();
nit: dyn_cast followed by (!inputRankedType) instead of hasRank followed by cast.

2023-01-14 00:30 UTC, smit-hinsu commented on stablehlo/dialect/TypeInference.cpp
> +                                              inputRankedType.getEncoding());
here, we need to infer the bounds as well depending on the strides, window size. Let me know if you need more inputs on this.

2023-01-17 03:19 UTC, burmako requested changes

2023-01-17 03:19 UTC, burmako commented on stablehlo/dialect/TypeInference.cpp
> +      if (encodingToBounds(inputRankedType.getEncoding()).empty()) {
Let's create a temporary variable for `encodingToBounds(inputRankedType.getEncoding())`. This is a non-trivial expression that is used multiple times.

2023-01-17 03:19 UTC, burmako commented on stablehlo/dialect/TypeInference.cpp
> +            encodingToBounds(inputRankedType.getEncoding()).vec(),
I don't think `.vec()` is needed here.

2023-01-17 03:19 UTC, burmako commented on stablehlo/tests/infer_stablehlo.mlir
> +    %arg1: tensor<?x?xi32, #stablehlo.type_extensions<bounds = [5, 3]>>,
Do we need to have both %arg0 and %arg1? It sounds like just one of them would be sufficient to test the new functionality introduced in this PR?

2023-01-17 03:19 UTC, burmako commented on stablehlo/tests/infer_stablehlo.mlir
> +func.func @reduce_window_bound_mixed(%arg0: tensor<4x?x?xf32, #stablehlo.type_extensions<bounds = [?, ?, 2]>>,
Can this test be merged with the previous test?

2023-01-17 20:48 UTC, burmako approved these changes

2023-01-17 21:52 UTC, merged