Infer bounds for AllToAllOp.
openxla/stablehlo pull request #921
Opened 2023-01-12 03:12 UTC by subhankarshah

draft

closes #801.

2023-01-13 04:33 UTC, zhouxin913 reviewed
LGTM.

add @smit-hinsu and @burmako for review.

2023-01-13 04:33 UTC, zhouxin913 commented on stablehlo/tests/infer_stablehlo.mlir
> +func.func @alltoallbounds(%data: tensor<16x?xf32, #stablehlo.type_extensions<bounds = [?, 5]>>) -> tensor<*xindex> {
-> alltoall_bounds

2023-01-17 03:43 UTC, burmako requested changes

2023-01-17 03:43 UTC, burmako commented on stablehlo/dialect/TypeInference.cpp
> +      isDynamicDimSize(resultShape[concatDimension]) ? 1 : splitCount;
Please rebase now that #922 is merged. This will pull in the logic that already implements this part.

2023-01-17 21:29 UTC, merged