Remove InferReturnTypeComponents test pattern from hlo_test_infer.
openxla/stablehlo pull request #960
Opened 2023-01-24 22:33 UTC by subhankarshah

* Move all usages of get_return_type_componets to get_return_types.

closes #938

2023-01-24 23:22 UTC, ghpvnist approved these changes
Minor comment.

2023-01-24 23:22 UTC, ghpvnist commented on stablehlo/tests/infer_stablehlo.mlir
> +  // CHECK: {types0 = tensor<1x2x3xf32>}
The CHECK directive is inconsistently above and below the %1. Can you stick to one version? Here and below.

2023-01-25 08:03 UTC, ghpvnist approved these changes

2023-01-25 16:16 UTC, burmako requested changes

2023-01-25 16:16 UTC, burmako commented on stablehlo/tests/infer_stablehlo.mlir
> +  // CHECK: %2 = "hlo_test_infer.return_types"(%1) {types0 = tensor<10x24x24x64xf32>} : (tensor<10x24x24x64xf32>) -> tensor<10x24x24x64xindex>
In the majority of this PR, we're using a simplified version of this CHECK, where only `typesN` are called out. Let's migrate everything to consistently do that?

2023-01-25 16:16 UTC, burmako commented on stablehlo/tests/infer_stablehlo.mlir
> +  // CHECK: %2 = "hlo_test_infer.return_types"(%1) {types0 = tensor<10x24x24x64xf32>} : (tensor<10x24x24x64xf32>) -> tensor<10x24x24x64xindex>
Also can we simplify `{types0 = tensor<10x24x24x64xf32>}` to just `types0 = tensor<10x24x24x64xf32>`? That would make things easier to read and write.

2023-01-25 20:37 UTC, burmako approved these changes

2023-01-25 20:45 UTC, merged